04-03 10:47:53 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 10:47:54 uvicorn.error INFO     Started server process [21196]
04-03 10:47:54 uvicorn.error INFO     Waiting for application startup.
04-03 10:47:54 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 10:47:54 uvicorn.error INFO     Application startup complete.
04-03 10:47:54 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 10:47:56 uvicorn.access INFO     192.168.103.48:60298 - "GET /welcome/ HTTP/1.1" 302
04-03 10:47:56 uvicorn.access INFO     192.168.103.48:60298 - "GET /home/index2/ HTTP/1.1" 200
04-03 10:47:57 uvicorn.access INFO     192.168.103.48:60298 - "GET /static/assets/css/style.css HTTP/1.1" 200
04-03 10:49:29 uvicorn.access INFO     192.168.103.48:60328 - "GET /welcome/logout/ HTTP/1.1" 302
04-03 10:49:29 uvicorn.access INFO     192.168.103.48:60328 - "GET /home/index2/ HTTP/1.1" 200
04-03 10:49:45 uvicorn.access INFO     192.168.103.48:60344 - "GET /welcome/login/ HTTP/1.1" 200
04-03 10:51:37 uvicorn.access INFO     192.168.103.48:60408 - "GET /welcome/login/ HTTP/1.1" 200
04-03 10:51:48 uvicorn.access INFO     192.168.103.48:60422 - "POST /welcome/login/ HTTP/1.1" 302
04-03 10:51:48 uvicorn.access INFO     192.168.103.48:60422 - "GET /home/index2/ HTTP/1.1" 200
04-03 10:51:58 uvicorn.access INFO     192.168.103.48:60429 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 10:58:49 uvicorn.error INFO     Shutting down
04-03 10:58:49 uvicorn.error INFO     Finished server process [21196]
04-03 10:58:58 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 10:58:59 uvicorn.error INFO     Started server process [15856]
04-03 10:58:59 uvicorn.error INFO     Waiting for application startup.
04-03 10:58:59 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 10:58:59 uvicorn.error INFO     Application startup complete.
04-03 10:58:59 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 10:59:02 uvicorn.access INFO     192.168.103.48:60501 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 10:59:20 uvicorn.error INFO     Shutting down
04-03 10:59:20 uvicorn.error INFO     Finished server process [15856]
04-03 10:59:28 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 10:59:28 uvicorn.error INFO     Started server process [6148]
04-03 10:59:28 uvicorn.error INFO     Waiting for application startup.
04-03 10:59:28 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 10:59:28 uvicorn.error INFO     Application startup complete.
04-03 10:59:28 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 10:59:32 uvicorn.access INFO     192.168.103.48:60510 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 11:00:11 uvicorn.error INFO     Shutting down
04-03 11:00:12 uvicorn.error INFO     Finished server process [6148]
04-03 11:00:17 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 11:00:18 uvicorn.error INFO     Started server process [14700]
04-03 11:00:18 uvicorn.error INFO     Waiting for application startup.
04-03 11:00:18 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 11:00:18 uvicorn.error INFO     Application startup complete.
04-03 11:00:18 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 11:00:19 uvicorn.access INFO     192.168.103.48:60517 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 11:06:39 uvicorn.error INFO     Shutting down
04-03 11:06:39 uvicorn.error INFO     Finished server process [14700]
04-03 11:06:44 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 11:06:45 uvicorn.error INFO     Started server process [6420]
04-03 11:06:45 uvicorn.error INFO     Waiting for application startup.
04-03 11:06:45 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 11:06:45 uvicorn.error INFO     Application startup complete.
04-03 11:06:45 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 11:06:46 uvicorn.access INFO     192.168.103.48:60539 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 11:09:35 uvicorn.error INFO     Shutting down
04-03 11:09:35 uvicorn.error INFO     Finished server process [6420]
04-03 11:09:40 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 11:09:41 uvicorn.error INFO     Started server process [22924]
04-03 11:09:41 uvicorn.error INFO     Waiting for application startup.
04-03 11:09:41 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 11:09:41 uvicorn.error INFO     Application startup complete.
04-03 11:09:41 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 11:09:44 uvicorn.access INFO     192.168.103.48:60545 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 11:10:44 uvicorn.error INFO     Shutting down
04-03 11:10:44 uvicorn.error INFO     Finished server process [22924]
04-03 11:10:46 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 11:10:47 uvicorn.error INFO     Started server process [18620]
04-03 11:10:47 uvicorn.error INFO     Waiting for application startup.
04-03 11:10:47 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 11:10:47 uvicorn.error INFO     Application startup complete.
04-03 11:10:47 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 11:10:49 uvicorn.access INFO     192.168.103.48:60551 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 11:11:33 uvicorn.error INFO     Shutting down
04-03 11:11:33 uvicorn.error INFO     Finished server process [18620]
04-03 11:11:37 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 11:11:38 uvicorn.error INFO     Started server process [26596]
04-03 11:11:38 uvicorn.error INFO     Waiting for application startup.
04-03 11:11:38 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 11:11:38 uvicorn.error INFO     Application startup complete.
04-03 11:11:38 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 11:11:40 uvicorn.access INFO     192.168.103.48:60566 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 11:13:15 uvicorn.error INFO     Shutting down
04-03 11:13:15 uvicorn.error INFO     Finished server process [26596]
04-03 11:13:21 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 11:13:22 uvicorn.error INFO     Started server process [20680]
04-03 11:13:22 uvicorn.error INFO     Waiting for application startup.
04-03 11:13:22 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 11:13:22 uvicorn.error INFO     Application startup complete.
04-03 11:13:22 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 11:13:24 uvicorn.access INFO     192.168.103.48:60572 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 11:15:45 uvicorn.error INFO     Shutting down
04-03 11:15:45 uvicorn.error INFO     Finished server process [20680]
04-03 11:15:49 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 11:15:50 uvicorn.error INFO     Started server process [13640]
04-03 11:15:50 uvicorn.error INFO     Waiting for application startup.
04-03 11:15:50 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 11:15:50 uvicorn.error INFO     Application startup complete.
04-03 11:15:50 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 11:15:52 uvicorn.access INFO     192.168.103.48:60580 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 11:16:10 uvicorn.error INFO     Shutting down
04-03 11:16:10 uvicorn.error INFO     Finished server process [13640]
04-03 11:16:15 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 11:16:16 uvicorn.error INFO     Started server process [25332]
04-03 11:16:16 uvicorn.error INFO     Waiting for application startup.
04-03 11:16:16 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 11:16:16 uvicorn.error INFO     Application startup complete.
04-03 11:16:16 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 11:16:19 uvicorn.access INFO     192.168.103.48:60588 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 11:19:52 uvicorn.access INFO     192.168.103.48:60603 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 11:20:05 uvicorn.error INFO     Shutting down
04-03 11:20:05 uvicorn.error INFO     Finished server process [25332]
04-03 11:20:10 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 11:20:11 uvicorn.error INFO     Started server process [11028]
04-03 11:20:11 uvicorn.error INFO     Waiting for application startup.
04-03 11:20:11 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 11:20:11 uvicorn.error INFO     Application startup complete.
04-03 11:20:11 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 11:20:15 uvicorn.access INFO     192.168.103.48:60607 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 11:23:18 uvicorn.access INFO     192.168.103.48:60612 - "GET /home/index2/ HTTP/1.1" 200
04-03 11:23:22 uvicorn.access INFO     192.168.103.48:60612 - "GET /home/student-grades/ HTTP/1.1" 200
04-03 11:23:27 uvicorn.access INFO     192.168.103.48:60612 - "GET /home/student-information/ HTTP/1.1" 200
04-03 11:23:42 uvicorn.access INFO     192.168.103.48:60613 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 11:36:57 uvicorn.access INFO     192.168.103.48:60650 - "GET /home/student-grades/ HTTP/1.1" 200
04-03 11:37:01 uvicorn.access INFO     192.168.103.48:60650 - "GET /home/index2/ HTTP/1.1" 200
04-03 11:37:39 uvicorn.access INFO     192.168.103.48:60651 - "GET /home/student-grades/ HTTP/1.1" 200
04-03 13:14:40 uvicorn.error INFO     Shutting down
04-03 13:14:40 uvicorn.error INFO     Finished server process [11028]
04-03 13:14:46 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 13:14:46 uvicorn.error INFO     Started server process [21264]
04-03 13:14:46 uvicorn.error INFO     Waiting for application startup.
04-03 13:14:46 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 13:14:46 uvicorn.error INFO     Application startup complete.
04-03 13:14:46 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 13:14:49 uvicorn.access INFO     192.168.103.48:60869 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 13:15:26 uvicorn.error INFO     Shutting down
04-03 13:15:26 uvicorn.error INFO     Finished server process [21264]
04-03 13:15:30 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 13:15:31 uvicorn.error INFO     Started server process [10128]
04-03 13:15:31 uvicorn.error INFO     Waiting for application startup.
04-03 13:15:31 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 13:15:31 uvicorn.error INFO     Application startup complete.
04-03 13:15:31 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 13:15:33 uvicorn.access INFO     192.168.103.48:60876 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 13:18:08 uvicorn.error INFO     Shutting down
04-03 13:18:08 uvicorn.error INFO     Finished server process [10128]
04-03 13:18:12 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 13:18:12 uvicorn.error INFO     Started server process [16928]
04-03 13:18:12 uvicorn.error INFO     Waiting for application startup.
04-03 13:18:12 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 13:18:12 uvicorn.error INFO     Application startup complete.
04-03 13:18:12 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 13:18:14 uvicorn.access INFO     192.168.103.48:60882 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 13:30:22 uvicorn.error INFO     Shutting down
04-03 13:30:22 uvicorn.error INFO     Finished server process [16928]
04-03 13:30:26 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 13:30:26 uvicorn.error INFO     Started server process [26424]
04-03 13:30:26 uvicorn.error INFO     Waiting for application startup.
04-03 13:30:26 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 13:30:26 uvicorn.error INFO     Application startup complete.
04-03 13:30:26 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 13:30:28 uvicorn.access INFO     192.168.103.48:61041 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 13:32:31 uvicorn.error INFO     Shutting down
04-03 13:32:31 uvicorn.error INFO     Finished server process [26424]
04-03 13:32:34 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 13:32:34 uvicorn.error INFO     Started server process [26976]
04-03 13:32:34 uvicorn.error INFO     Waiting for application startup.
04-03 13:32:34 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 13:32:34 uvicorn.error INFO     Application startup complete.
04-03 13:32:34 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 13:32:36 uvicorn.access INFO     192.168.103.48:61054 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 13:52:35 uvicorn.error INFO     Shutting down
04-03 13:52:35 uvicorn.error INFO     Finished server process [26976]
04-03 13:52:38 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 13:52:38 uvicorn.error INFO     Started server process [23756]
04-03 13:52:38 uvicorn.error INFO     Waiting for application startup.
04-03 13:52:38 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 13:52:38 uvicorn.error INFO     Application startup complete.
04-03 13:52:38 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 13:52:42 uvicorn.access INFO     192.168.103.48:61116 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 13:54:06 uvicorn.error INFO     Shutting down
04-03 13:54:06 uvicorn.error INFO     Finished server process [23756]
04-03 13:54:10 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 13:54:10 uvicorn.error INFO     Started server process [25864]
04-03 13:54:10 uvicorn.error INFO     Waiting for application startup.
04-03 13:54:10 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 13:54:10 uvicorn.error INFO     Application startup complete.
04-03 13:54:10 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 13:54:13 uvicorn.access INFO     192.168.103.48:61122 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 13:55:12 uvicorn.error INFO     Shutting down
04-03 13:55:12 uvicorn.error INFO     Finished server process [25864]
04-03 13:55:15 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 13:55:16 uvicorn.error INFO     Started server process [26432]
04-03 13:55:16 uvicorn.error INFO     Waiting for application startup.
04-03 13:55:16 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 13:55:16 uvicorn.error INFO     Application startup complete.
04-03 13:55:16 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 13:55:20 uvicorn.access INFO     192.168.103.48:61127 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 13:55:50 uvicorn.error INFO     Shutting down
04-03 13:55:50 uvicorn.error INFO     Finished server process [26432]
04-03 13:55:53 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 13:55:54 uvicorn.error INFO     Started server process [25616]
04-03 13:55:54 uvicorn.error INFO     Waiting for application startup.
04-03 13:55:54 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 13:55:54 uvicorn.error INFO     Application startup complete.
04-03 13:55:54 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 13:55:56 uvicorn.access INFO     192.168.103.48:61133 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 13:57:39 uvicorn.error INFO     Shutting down
04-03 13:57:40 uvicorn.error INFO     Finished server process [25616]
04-03 13:57:43 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 13:57:43 uvicorn.error INFO     Started server process [13780]
04-03 13:57:43 uvicorn.error INFO     Waiting for application startup.
04-03 13:57:43 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 13:57:43 uvicorn.error INFO     Application startup complete.
04-03 13:57:43 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 13:57:46 uvicorn.access INFO     192.168.103.48:61139 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 13:58:20 uvicorn.error INFO     Shutting down
04-03 13:58:20 uvicorn.error INFO     Finished server process [13780]
04-03 13:58:23 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 13:58:24 uvicorn.error INFO     Started server process [26020]
04-03 13:58:24 uvicorn.error INFO     Waiting for application startup.
04-03 13:58:24 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 13:58:24 uvicorn.error INFO     Application startup complete.
04-03 13:58:24 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 13:58:26 uvicorn.access INFO     192.168.103.48:61143 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 13:59:44 uvicorn.error INFO     Shutting down
04-03 13:59:44 uvicorn.error INFO     Finished server process [26020]
04-03 13:59:49 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 13:59:49 uvicorn.error INFO     Started server process [17832]
04-03 13:59:49 uvicorn.error INFO     Waiting for application startup.
04-03 13:59:49 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 13:59:49 uvicorn.error INFO     Application startup complete.
04-03 13:59:49 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 13:59:51 uvicorn.access INFO     192.168.103.48:61149 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:02:57 uvicorn.error INFO     Shutting down
04-03 14:02:58 uvicorn.error INFO     Finished server process [17832]
04-03 14:03:02 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:03:02 uvicorn.error INFO     Started server process [15684]
04-03 14:03:02 uvicorn.error INFO     Waiting for application startup.
04-03 14:03:02 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:03:02 uvicorn.error INFO     Application startup complete.
04-03 14:03:02 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:03:04 uvicorn.access INFO     192.168.103.48:61177 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:09:10 uvicorn.error INFO     Shutting down
04-03 14:09:10 uvicorn.error INFO     Finished server process [15684]
04-03 14:09:35 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:09:36 uvicorn.error INFO     Started server process [13640]
04-03 14:09:36 uvicorn.error INFO     Waiting for application startup.
04-03 14:09:36 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:09:36 uvicorn.error INFO     Application startup complete.
04-03 14:09:36 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:09:38 uvicorn.access INFO     192.168.103.48:61201 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:12:47 uvicorn.access INFO     192.168.103.48:61206 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:13:03 uvicorn.error INFO     Shutting down
04-03 14:13:03 uvicorn.error INFO     Finished server process [13640]
04-03 14:13:07 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:13:08 uvicorn.error INFO     Started server process [13820]
04-03 14:13:08 uvicorn.error INFO     Waiting for application startup.
04-03 14:13:08 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:13:08 uvicorn.error INFO     Application startup complete.
04-03 14:13:08 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:13:12 uvicorn.access INFO     192.168.103.48:61210 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:14:15 uvicorn.access INFO     192.168.103.48:61212 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:14:35 uvicorn.access INFO     192.168.103.48:61213 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:15:06 uvicorn.error INFO     Shutting down
04-03 14:15:06 uvicorn.error INFO     Finished server process [13820]
04-03 14:15:09 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:15:10 uvicorn.error INFO     Started server process [26796]
04-03 14:15:10 uvicorn.error INFO     Waiting for application startup.
04-03 14:15:10 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:15:10 uvicorn.error INFO     Application startup complete.
04-03 14:15:10 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:15:12 uvicorn.access INFO     192.168.103.48:61218 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:16:12 uvicorn.access INFO     192.168.103.48:61219 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:16:29 uvicorn.error INFO     Shutting down
04-03 14:16:29 uvicorn.error INFO     Finished server process [26796]
04-03 14:16:32 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:16:33 uvicorn.error INFO     Started server process [18472]
04-03 14:16:33 uvicorn.error INFO     Waiting for application startup.
04-03 14:16:33 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:16:33 uvicorn.error INFO     Application startup complete.
04-03 14:16:33 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:16:36 uvicorn.access INFO     192.168.103.48:61223 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:18:03 uvicorn.error INFO     Shutting down
04-03 14:18:03 uvicorn.error INFO     Finished server process [18472]
04-03 14:18:06 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:18:08 uvicorn.error INFO     Started server process [17860]
04-03 14:18:08 uvicorn.error INFO     Waiting for application startup.
04-03 14:18:08 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:18:08 uvicorn.error INFO     Application startup complete.
04-03 14:18:08 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:18:09 uvicorn.access INFO     192.168.103.48:61233 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:21:45 uvicorn.error INFO     Shutting down
04-03 14:21:45 uvicorn.error INFO     Finished server process [17860]
04-03 14:21:51 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:21:52 uvicorn.error INFO     Started server process [15652]
04-03 14:21:52 uvicorn.error INFO     Waiting for application startup.
04-03 14:21:52 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:21:52 uvicorn.error INFO     Application startup complete.
04-03 14:21:52 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:21:55 uvicorn.access INFO     192.168.103.48:61241 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:22:44 uvicorn.error INFO     Shutting down
04-03 14:22:45 uvicorn.error INFO     Finished server process [15652]
04-03 14:22:48 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:22:48 uvicorn.error INFO     Started server process [3520]
04-03 14:22:48 uvicorn.error INFO     Waiting for application startup.
04-03 14:22:48 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:22:48 uvicorn.error INFO     Application startup complete.
04-03 14:22:48 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:22:51 uvicorn.access INFO     192.168.103.48:61246 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:24:17 uvicorn.error INFO     Shutting down
04-03 14:24:17 uvicorn.error INFO     Finished server process [3520]
04-03 14:24:20 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:24:20 uvicorn.error INFO     Started server process [8540]
04-03 14:24:20 uvicorn.error INFO     Waiting for application startup.
04-03 14:24:20 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:24:20 uvicorn.error INFO     Application startup complete.
04-03 14:24:20 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:24:24 uvicorn.access INFO     192.168.103.48:61254 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:26:15 uvicorn.error INFO     Shutting down
04-03 14:26:15 uvicorn.error INFO     Finished server process [8540]
04-03 14:26:17 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:26:17 uvicorn.error INFO     Started server process [7064]
04-03 14:26:17 uvicorn.error INFO     Waiting for application startup.
04-03 14:26:17 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:26:17 uvicorn.error INFO     Application startup complete.
04-03 14:26:17 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:26:19 uvicorn.access INFO     192.168.103.48:61265 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:27:31 uvicorn.error INFO     Shutting down
04-03 14:27:32 uvicorn.error INFO     Finished server process [7064]
04-03 14:27:35 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:27:35 uvicorn.error INFO     Started server process [14148]
04-03 14:27:35 uvicorn.error INFO     Waiting for application startup.
04-03 14:27:35 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:27:35 uvicorn.error INFO     Application startup complete.
04-03 14:27:35 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:27:37 uvicorn.access INFO     192.168.103.48:61269 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:31:33 uvicorn.error INFO     Shutting down
04-03 14:31:33 uvicorn.error INFO     Finished server process [14148]
04-03 14:31:37 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:31:38 uvicorn.error INFO     Started server process [17228]
04-03 14:31:38 uvicorn.error INFO     Waiting for application startup.
04-03 14:31:38 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:31:38 uvicorn.error INFO     Application startup complete.
04-03 14:31:38 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:31:40 uvicorn.access INFO     192.168.103.48:61281 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:31:58 uvicorn.error INFO     Shutting down
04-03 14:31:58 uvicorn.error INFO     Finished server process [17228]
04-03 14:32:00 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:32:00 uvicorn.error INFO     Started server process [9480]
04-03 14:32:00 uvicorn.error INFO     Waiting for application startup.
04-03 14:32:00 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:32:00 uvicorn.error INFO     Application startup complete.
04-03 14:32:00 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:32:02 uvicorn.access INFO     192.168.103.48:61288 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:32:56 uvicorn.error INFO     Shutting down
04-03 14:32:56 uvicorn.error INFO     Finished server process [9480]
04-03 14:32:59 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:33:00 uvicorn.error INFO     Started server process [20700]
04-03 14:33:00 uvicorn.error INFO     Waiting for application startup.
04-03 14:33:00 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:33:00 uvicorn.error INFO     Application startup complete.
04-03 14:33:00 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:33:02 uvicorn.access INFO     192.168.103.48:61292 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:38:40 uvicorn.error INFO     Shutting down
04-03 14:38:40 uvicorn.error INFO     Finished server process [20700]
04-03 14:38:43 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:38:43 uvicorn.error INFO     Started server process [23928]
04-03 14:38:43 uvicorn.error INFO     Waiting for application startup.
04-03 14:38:43 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:38:43 uvicorn.error INFO     Application startup complete.
04-03 14:38:43 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:38:45 uvicorn.access INFO     192.168.103.48:61306 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:39:35 uvicorn.error INFO     Shutting down
04-03 14:39:35 uvicorn.error INFO     Finished server process [23928]
04-03 14:39:38 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:39:38 uvicorn.error INFO     Started server process [14400]
04-03 14:39:38 uvicorn.error INFO     Waiting for application startup.
04-03 14:39:38 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:39:38 uvicorn.error INFO     Application startup complete.
04-03 14:39:38 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:39:40 uvicorn.access INFO     192.168.103.48:61310 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:41:56 uvicorn.error INFO     Shutting down
04-03 14:41:56 uvicorn.error INFO     Finished server process [14400]
04-03 14:42:00 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:42:00 uvicorn.error INFO     Started server process [16220]
04-03 14:42:00 uvicorn.error INFO     Waiting for application startup.
04-03 14:42:00 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:42:00 uvicorn.error INFO     Application startup complete.
04-03 14:42:00 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:42:02 uvicorn.access INFO     192.168.103.48:61314 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:46:01 uvicorn.error INFO     Shutting down
04-03 14:46:01 uvicorn.error INFO     Finished server process [16220]
04-03 14:46:04 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:46:04 uvicorn.error INFO     Started server process [3060]
04-03 14:46:04 uvicorn.error INFO     Waiting for application startup.
04-03 14:46:04 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:46:04 uvicorn.error INFO     Application startup complete.
04-03 14:46:04 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:46:07 uvicorn.access INFO     192.168.103.48:61324 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:47:21 uvicorn.error INFO     Shutting down
04-03 14:47:21 uvicorn.error INFO     Finished server process [3060]
04-03 14:47:24 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:47:24 uvicorn.error INFO     Started server process [23076]
04-03 14:47:24 uvicorn.error INFO     Waiting for application startup.
04-03 14:47:24 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:47:24 uvicorn.error INFO     Application startup complete.
04-03 14:47:24 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:47:26 uvicorn.access INFO     192.168.103.48:61329 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:52:17 uvicorn.error INFO     Shutting down
04-03 14:52:17 uvicorn.error INFO     Finished server process [23076]
04-03 14:52:22 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:52:23 uvicorn.error INFO     Started server process [6580]
04-03 14:52:23 uvicorn.error INFO     Waiting for application startup.
04-03 14:52:23 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:52:23 uvicorn.error INFO     Application startup complete.
04-03 14:52:23 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:52:28 uvicorn.access INFO     192.168.103.48:61337 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 14:52:50 uvicorn.error INFO     Shutting down
04-03 14:52:50 uvicorn.error INFO     Finished server process [6580]
04-03 14:52:53 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 14:52:54 uvicorn.error INFO     Started server process [26860]
04-03 14:52:54 uvicorn.error INFO     Waiting for application startup.
04-03 14:52:54 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 14:52:54 uvicorn.error INFO     Application startup complete.
04-03 14:52:54 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 14:52:56 uvicorn.access INFO     192.168.103.48:61341 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:02:16 uvicorn.error INFO     Shutting down
04-03 15:02:16 uvicorn.error INFO     Finished server process [26860]
04-03 15:02:24 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:02:24 uvicorn.error INFO     Started server process [24388]
04-03 15:02:24 uvicorn.error INFO     Waiting for application startup.
04-03 15:02:24 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:02:24 uvicorn.error INFO     Application startup complete.
04-03 15:02:24 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:02:30 uvicorn.access INFO     192.168.103.48:61367 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:03:57 uvicorn.error INFO     Shutting down
04-03 15:03:57 uvicorn.error INFO     Finished server process [24388]
04-03 15:04:01 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:04:01 uvicorn.error INFO     Started server process [11016]
04-03 15:04:01 uvicorn.error INFO     Waiting for application startup.
04-03 15:04:01 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:04:01 uvicorn.error INFO     Application startup complete.
04-03 15:04:01 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:04:03 uvicorn.access INFO     192.168.103.48:61374 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:04:54 uvicorn.error INFO     Shutting down
04-03 15:04:54 uvicorn.error INFO     Finished server process [11016]
04-03 15:04:57 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:04:57 uvicorn.error INFO     Started server process [10752]
04-03 15:04:57 uvicorn.error INFO     Waiting for application startup.
04-03 15:04:57 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:04:57 uvicorn.error INFO     Application startup complete.
04-03 15:04:57 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:05:00 uvicorn.access INFO     192.168.103.48:61378 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:05:33 uvicorn.error INFO     Shutting down
04-03 15:05:33 uvicorn.error INFO     Finished server process [10752]
04-03 15:05:36 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:05:37 uvicorn.error INFO     Started server process [22656]
04-03 15:05:37 uvicorn.error INFO     Waiting for application startup.
04-03 15:05:37 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:05:37 uvicorn.error INFO     Application startup complete.
04-03 15:05:37 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:05:38 uvicorn.access INFO     192.168.103.48:61384 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:17:34 uvicorn.error INFO     Shutting down
04-03 15:17:34 uvicorn.error INFO     Finished server process [22656]
04-03 15:17:39 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:17:39 uvicorn.error INFO     Started server process [15828]
04-03 15:17:39 uvicorn.error INFO     Waiting for application startup.
04-03 15:17:39 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:17:39 uvicorn.error INFO     Application startup complete.
04-03 15:17:39 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:17:42 uvicorn.access INFO     192.168.103.48:61464 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:18:09 uvicorn.error INFO     Shutting down
04-03 15:18:09 uvicorn.error INFO     Finished server process [15828]
04-03 15:18:11 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:18:11 uvicorn.error INFO     Started server process [23956]
04-03 15:18:11 uvicorn.error INFO     Waiting for application startup.
04-03 15:18:11 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:18:11 uvicorn.error INFO     Application startup complete.
04-03 15:18:11 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:18:13 uvicorn.access INFO     192.168.103.48:61468 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:18:30 uvicorn.error INFO     Shutting down
04-03 15:18:30 uvicorn.error INFO     Finished server process [23956]
04-03 15:18:33 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:18:33 uvicorn.error INFO     Started server process [12472]
04-03 15:18:33 uvicorn.error INFO     Waiting for application startup.
04-03 15:18:33 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:18:33 uvicorn.error INFO     Application startup complete.
04-03 15:18:33 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:18:36 uvicorn.access INFO     192.168.103.48:61472 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:18:58 uvicorn.error INFO     Shutting down
04-03 15:18:58 uvicorn.error INFO     Finished server process [12472]
04-03 15:19:02 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:19:02 uvicorn.error INFO     Started server process [11192]
04-03 15:19:02 uvicorn.error INFO     Waiting for application startup.
04-03 15:19:02 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:19:02 uvicorn.error INFO     Application startup complete.
04-03 15:19:02 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:19:04 uvicorn.access INFO     192.168.103.48:61476 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:19:57 uvicorn.access INFO     192.168.103.48:61477 - "GET /welcome/logout/ HTTP/1.1" 302
04-03 15:19:57 uvicorn.access INFO     192.168.103.48:61477 - "GET /home/index2/ HTTP/1.1" 200
04-03 15:20:00 uvicorn.access INFO     192.168.103.48:61477 - "GET /welcome/login/ HTTP/1.1" 200
04-03 15:24:05 uvicorn.error INFO     Shutting down
04-03 15:24:05 uvicorn.error INFO     Finished server process [11192]
04-03 15:24:08 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:24:09 uvicorn.error INFO     Started server process [26992]
04-03 15:24:09 uvicorn.error INFO     Waiting for application startup.
04-03 15:24:09 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:24:09 uvicorn.error INFO     Application startup complete.
04-03 15:24:09 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:24:12 uvicorn.access INFO     192.168.103.48:61487 - "GET /welcome/login/ HTTP/1.1" 200
04-03 15:25:49 uvicorn.error INFO     Shutting down
04-03 15:25:49 uvicorn.error INFO     Finished server process [26992]
04-03 15:25:57 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:25:58 uvicorn.error INFO     Started server process [7856]
04-03 15:25:58 uvicorn.error INFO     Waiting for application startup.
04-03 15:25:58 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:25:58 uvicorn.error INFO     Application startup complete.
04-03 15:25:58 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:26:01 uvicorn.access INFO     192.168.103.48:61492 - "GET /welcome/login/ HTTP/1.1" 200
04-03 15:26:41 uvicorn.error INFO     Shutting down
04-03 15:26:41 uvicorn.error INFO     Finished server process [7856]
04-03 15:26:43 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:26:44 uvicorn.error INFO     Started server process [20468]
04-03 15:26:44 uvicorn.error INFO     Waiting for application startup.
04-03 15:26:44 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:26:44 uvicorn.error INFO     Application startup complete.
04-03 15:26:44 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:26:46 uvicorn.access INFO     192.168.103.48:61498 - "GET /welcome/login/ HTTP/1.1" 200
04-03 15:27:20 uvicorn.error INFO     Shutting down
04-03 15:27:20 uvicorn.error INFO     Finished server process [20468]
04-03 15:27:22 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:27:23 uvicorn.error INFO     Started server process [5864]
04-03 15:27:23 uvicorn.error INFO     Waiting for application startup.
04-03 15:27:23 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:27:23 uvicorn.error INFO     Application startup complete.
04-03 15:27:23 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:27:26 uvicorn.access INFO     192.168.103.48:61504 - "GET /welcome/login/ HTTP/1.1" 200
04-03 15:28:19 uvicorn.error INFO     Shutting down
04-03 15:28:19 uvicorn.error INFO     Finished server process [5864]
04-03 15:28:21 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:28:22 uvicorn.error INFO     Started server process [18020]
04-03 15:28:22 uvicorn.error INFO     Waiting for application startup.
04-03 15:28:22 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:28:22 uvicorn.error INFO     Application startup complete.
04-03 15:28:22 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:28:26 uvicorn.access INFO     192.168.103.48:61509 - "GET /welcome/login/ HTTP/1.1" 200
04-03 15:30:49 uvicorn.error INFO     Shutting down
04-03 15:30:50 uvicorn.error INFO     Finished server process [18020]
04-03 15:30:53 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:30:54 uvicorn.error INFO     Started server process [17044]
04-03 15:30:54 uvicorn.error INFO     Waiting for application startup.
04-03 15:30:54 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:30:54 uvicorn.error INFO     Application startup complete.
04-03 15:30:54 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:30:59 uvicorn.access INFO     192.168.103.48:61522 - "GET /welcome/login/ HTTP/1.1" 200
04-03 15:32:21 uvicorn.error INFO     Shutting down
04-03 15:32:21 uvicorn.error INFO     Finished server process [17044]
04-03 15:32:24 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:32:25 uvicorn.error INFO     Started server process [9592]
04-03 15:32:25 uvicorn.error INFO     Waiting for application startup.
04-03 15:32:25 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:32:25 uvicorn.error INFO     Application startup complete.
04-03 15:32:25 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:32:27 uvicorn.access INFO     192.168.103.48:61533 - "GET /welcome/login/ HTTP/1.1" 200
04-03 15:33:13 uvicorn.error INFO     Shutting down
04-03 15:33:13 uvicorn.error INFO     Finished server process [9592]
04-03 15:33:15 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:33:16 uvicorn.error INFO     Started server process [13712]
04-03 15:33:16 uvicorn.error INFO     Waiting for application startup.
04-03 15:33:16 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:33:16 uvicorn.error INFO     Application startup complete.
04-03 15:33:16 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:33:18 uvicorn.access INFO     192.168.103.48:61542 - "GET /welcome/login/ HTTP/1.1" 200
04-03 15:33:29 uvicorn.access INFO     192.168.103.48:61543 - "POST /welcome/login/ HTTP/1.1" 302
04-03 15:33:29 uvicorn.access INFO     192.168.103.48:61543 - "GET /home/index2/ HTTP/1.1" 200
04-03 15:33:32 uvicorn.access INFO     192.168.103.48:61543 - "GET /home/student-grades/ HTTP/1.1" 200
04-03 15:33:36 uvicorn.access INFO     192.168.103.48:61543 - "GET /home/index2/ HTTP/1.1" 200
04-03 15:33:39 uvicorn.access INFO     192.168.103.48:61543 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:34:36 uvicorn.error INFO     Shutting down
04-03 15:34:36 uvicorn.error INFO     Finished server process [13712]
04-03 15:34:40 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:34:40 uvicorn.error INFO     Started server process [7912]
04-03 15:34:40 uvicorn.error INFO     Waiting for application startup.
04-03 15:34:40 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:34:40 uvicorn.error INFO     Application startup complete.
04-03 15:34:40 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:34:42 uvicorn.access INFO     192.168.103.48:61559 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:35:35 uvicorn.access INFO     192.168.103.48:61560 - "GET /home/student-information/ HTTP/1.1" 200
04-03 15:35:39 uvicorn.access INFO     192.168.103.48:61560 - "GET /home/index2/ HTTP/1.1" 200
04-03 15:36:11 uvicorn.access INFO     192.168.103.48:61562 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:38:32 uvicorn.error INFO     Shutting down
04-03 15:38:32 uvicorn.error INFO     Finished server process [7912]
04-03 15:38:35 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:38:35 uvicorn.error INFO     Started server process [18568]
04-03 15:38:35 uvicorn.error INFO     Waiting for application startup.
04-03 15:38:35 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:38:35 uvicorn.error INFO     Application startup complete.
04-03 15:38:35 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:38:39 uvicorn.access INFO     192.168.103.48:61572 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:40:08 uvicorn.error INFO     Shutting down
04-03 15:40:08 uvicorn.error INFO     Finished server process [18568]
04-03 15:40:12 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:40:12 uvicorn.error INFO     Started server process [23736]
04-03 15:40:12 uvicorn.error INFO     Waiting for application startup.
04-03 15:40:12 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:40:12 uvicorn.error INFO     Application startup complete.
04-03 15:40:12 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:40:16 uvicorn.access INFO     192.168.103.48:61581 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:41:02 uvicorn.error INFO     Shutting down
04-03 15:41:03 uvicorn.error INFO     Finished server process [23736]
04-03 15:41:06 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:41:06 uvicorn.error INFO     Started server process [25440]
04-03 15:41:06 uvicorn.error INFO     Waiting for application startup.
04-03 15:41:06 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:41:06 uvicorn.error INFO     Application startup complete.
04-03 15:41:06 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:41:08 uvicorn.access INFO     192.168.103.48:61596 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:41:34 uvicorn.error INFO     Shutting down
04-03 15:41:34 uvicorn.error INFO     Finished server process [25440]
04-03 15:41:37 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:41:37 uvicorn.error INFO     Started server process [7352]
04-03 15:41:37 uvicorn.error INFO     Waiting for application startup.
04-03 15:41:37 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:41:37 uvicorn.error INFO     Application startup complete.
04-03 15:41:37 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:41:39 uvicorn.access INFO     192.168.103.48:61602 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:42:50 uvicorn.error INFO     Shutting down
04-03 15:42:50 uvicorn.error INFO     Finished server process [7352]
04-03 15:42:53 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:42:53 uvicorn.error INFO     Started server process [16112]
04-03 15:42:53 uvicorn.error INFO     Waiting for application startup.
04-03 15:42:53 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:42:53 uvicorn.error INFO     Application startup complete.
04-03 15:42:53 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:42:56 uvicorn.access INFO     192.168.103.48:61611 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:44:11 uvicorn.error INFO     Shutting down
04-03 15:44:11 uvicorn.error INFO     Finished server process [16112]
04-03 15:44:14 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:44:14 uvicorn.error INFO     Started server process [20908]
04-03 15:44:14 uvicorn.error INFO     Waiting for application startup.
04-03 15:44:14 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:44:14 uvicorn.error INFO     Application startup complete.
04-03 15:44:14 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:44:20 uvicorn.access INFO     192.168.103.48:61624 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:46:41 uvicorn.error INFO     Shutting down
04-03 15:46:41 uvicorn.error INFO     Finished server process [20908]
04-03 15:46:44 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:46:44 uvicorn.error INFO     Started server process [21624]
04-03 15:46:44 uvicorn.error INFO     Waiting for application startup.
04-03 15:46:44 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:46:44 uvicorn.error INFO     Application startup complete.
04-03 15:46:44 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:46:47 uvicorn.access INFO     192.168.103.48:61643 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:47:39 uvicorn.error INFO     Shutting down
04-03 15:47:39 uvicorn.error INFO     Finished server process [21624]
04-03 15:47:42 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:47:42 uvicorn.error INFO     Started server process [19516]
04-03 15:47:42 uvicorn.error INFO     Waiting for application startup.
04-03 15:47:42 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:47:42 uvicorn.error INFO     Application startup complete.
04-03 15:47:42 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:47:44 uvicorn.access INFO     192.168.103.48:61652 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:48:56 uvicorn.error INFO     Shutting down
04-03 15:48:56 uvicorn.error INFO     Finished server process [19516]
04-03 15:48:58 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:48:58 uvicorn.error INFO     Started server process [17500]
04-03 15:48:58 uvicorn.error INFO     Waiting for application startup.
04-03 15:48:58 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:48:58 uvicorn.error INFO     Application startup complete.
04-03 15:48:58 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:49:00 uvicorn.access INFO     192.168.103.48:61656 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:49:56 uvicorn.error INFO     Shutting down
04-03 15:49:56 uvicorn.error INFO     Finished server process [17500]
04-03 15:49:58 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:49:59 uvicorn.error INFO     Started server process [7008]
04-03 15:49:59 uvicorn.error INFO     Waiting for application startup.
04-03 15:49:59 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:49:59 uvicorn.error INFO     Application startup complete.
04-03 15:49:59 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:50:01 uvicorn.access INFO     192.168.103.48:61661 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:50:41 uvicorn.error INFO     Shutting down
04-03 15:50:41 uvicorn.error INFO     Finished server process [7008]
04-03 15:50:45 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:50:45 uvicorn.error INFO     Started server process [11192]
04-03 15:50:45 uvicorn.error INFO     Waiting for application startup.
04-03 15:50:45 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:50:45 uvicorn.error INFO     Application startup complete.
04-03 15:50:45 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:50:47 uvicorn.access INFO     192.168.103.48:61665 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:52:12 uvicorn.error INFO     Shutting down
04-03 15:52:12 uvicorn.error INFO     Finished server process [11192]
04-03 15:52:14 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:52:15 uvicorn.error INFO     Started server process [23032]
04-03 15:52:15 uvicorn.error INFO     Waiting for application startup.
04-03 15:52:15 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:52:15 uvicorn.error INFO     Application startup complete.
04-03 15:52:15 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:52:17 uvicorn.access INFO     192.168.103.48:61710 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:53:42 uvicorn.error INFO     Shutting down
04-03 15:53:42 uvicorn.error INFO     Finished server process [23032]
04-03 15:53:45 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:53:45 uvicorn.error INFO     Started server process [8884]
04-03 15:53:45 uvicorn.error INFO     Waiting for application startup.
04-03 15:53:45 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:53:45 uvicorn.error INFO     Application startup complete.
04-03 15:53:45 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:53:48 uvicorn.access INFO     192.168.103.48:61721 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 15:54:58 uvicorn.error INFO     Shutting down
04-03 15:54:58 uvicorn.error INFO     Finished server process [8884]
04-03 15:55:00 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 15:55:01 uvicorn.error INFO     Started server process [22020]
04-03 15:55:01 uvicorn.error INFO     Waiting for application startup.
04-03 15:55:01 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 15:55:01 uvicorn.error INFO     Application startup complete.
04-03 15:55:01 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 15:55:03 uvicorn.access INFO     192.168.103.48:61727 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:01:05 uvicorn.error INFO     Shutting down
04-03 16:01:05 uvicorn.error INFO     Finished server process [22020]
04-03 16:01:07 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:01:08 uvicorn.error INFO     Started server process [15796]
04-03 16:01:08 uvicorn.error INFO     Waiting for application startup.
04-03 16:01:08 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:01:08 uvicorn.error INFO     Application startup complete.
04-03 16:01:08 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:01:12 uvicorn.access INFO     192.168.103.48:61745 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:02:20 uvicorn.error INFO     Shutting down
04-03 16:02:20 uvicorn.error INFO     Finished server process [15796]
04-03 16:02:23 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:02:23 uvicorn.error INFO     Started server process [7236]
04-03 16:02:23 uvicorn.error INFO     Waiting for application startup.
04-03 16:02:23 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:02:23 uvicorn.error INFO     Application startup complete.
04-03 16:02:23 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:02:26 uvicorn.access INFO     192.168.103.48:61761 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:03:10 uvicorn.error INFO     Shutting down
04-03 16:03:10 uvicorn.error INFO     Finished server process [7236]
04-03 16:03:13 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:03:13 uvicorn.error INFO     Started server process [5872]
04-03 16:03:13 uvicorn.error INFO     Waiting for application startup.
04-03 16:03:13 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:03:13 uvicorn.error INFO     Application startup complete.
04-03 16:03:13 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:03:16 uvicorn.access INFO     192.168.103.48:61767 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:03:33 uvicorn.access INFO     192.168.103.48:61768 - "GET /home/student-grades/ HTTP/1.1" 200
04-03 16:03:35 uvicorn.access INFO     192.168.103.48:61768 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:04:06 uvicorn.error INFO     Shutting down
04-03 16:04:06 uvicorn.error INFO     Finished server process [5872]
04-03 16:04:08 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:04:09 uvicorn.error INFO     Started server process [26348]
04-03 16:04:09 uvicorn.error INFO     Waiting for application startup.
04-03 16:04:09 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:04:09 uvicorn.error INFO     Application startup complete.
04-03 16:04:09 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:04:11 uvicorn.access INFO     192.168.103.48:61774 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:04:56 uvicorn.error INFO     Shutting down
04-03 16:04:56 uvicorn.error INFO     Finished server process [26348]
04-03 16:04:59 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:05:00 uvicorn.error INFO     Started server process [14716]
04-03 16:05:00 uvicorn.error INFO     Waiting for application startup.
04-03 16:05:00 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:05:00 uvicorn.error INFO     Application startup complete.
04-03 16:05:00 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:05:02 uvicorn.access INFO     192.168.103.48:61779 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:05:49 uvicorn.error INFO     Shutting down
04-03 16:05:49 uvicorn.error INFO     Finished server process [14716]
04-03 16:05:52 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:05:52 uvicorn.error INFO     Started server process [4416]
04-03 16:05:52 uvicorn.error INFO     Waiting for application startup.
04-03 16:05:52 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:05:52 uvicorn.error INFO     Application startup complete.
04-03 16:05:52 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:05:55 uvicorn.access INFO     192.168.103.48:61783 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:06:15 uvicorn.error INFO     Shutting down
04-03 16:06:15 uvicorn.error INFO     Finished server process [4416]
04-03 16:06:18 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:06:19 uvicorn.error INFO     Started server process [1628]
04-03 16:06:19 uvicorn.error INFO     Waiting for application startup.
04-03 16:06:19 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:06:19 uvicorn.error INFO     Application startup complete.
04-03 16:06:19 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:06:22 uvicorn.access INFO     192.168.103.48:61787 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:10:32 uvicorn.error INFO     Shutting down
04-03 16:10:32 uvicorn.error INFO     Finished server process [1628]
04-03 16:10:35 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:10:35 uvicorn.error INFO     Started server process [10596]
04-03 16:10:35 uvicorn.error INFO     Waiting for application startup.
04-03 16:10:35 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:10:35 uvicorn.error INFO     Application startup complete.
04-03 16:10:35 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:10:39 uvicorn.access INFO     192.168.103.48:61807 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:11:39 uvicorn.error INFO     Shutting down
04-03 16:11:39 uvicorn.error INFO     Finished server process [10596]
04-03 16:11:41 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:11:42 uvicorn.error INFO     Started server process [26708]
04-03 16:11:42 uvicorn.error INFO     Waiting for application startup.
04-03 16:11:42 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:11:42 uvicorn.error INFO     Application startup complete.
04-03 16:11:42 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:11:44 uvicorn.access INFO     192.168.103.48:61811 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:12:48 uvicorn.error INFO     Shutting down
04-03 16:12:48 uvicorn.error INFO     Finished server process [26708]
04-03 16:12:51 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:12:51 uvicorn.error INFO     Started server process [27496]
04-03 16:12:51 uvicorn.error INFO     Waiting for application startup.
04-03 16:12:51 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:12:51 uvicorn.error INFO     Application startup complete.
04-03 16:12:51 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:12:57 uvicorn.access INFO     192.168.103.48:61815 - "GET /home/student-grades/ HTTP/1.1" 200
04-03 16:14:46 uvicorn.error INFO     Shutting down
04-03 16:14:46 uvicorn.error INFO     Finished server process [27496]
04-03 16:14:49 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:14:49 uvicorn.error INFO     Started server process [25652]
04-03 16:14:49 uvicorn.error INFO     Waiting for application startup.
04-03 16:14:49 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:14:49 uvicorn.error INFO     Application startup complete.
04-03 16:14:49 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:14:51 uvicorn.access INFO     192.168.103.48:61819 - "GET /home/student-grades/ HTTP/1.1" 200
04-03 16:16:54 uvicorn.error INFO     Shutting down
04-03 16:16:54 uvicorn.error INFO     Finished server process [25652]
04-03 16:16:57 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:16:58 uvicorn.error INFO     Started server process [27156]
04-03 16:16:58 uvicorn.error INFO     Waiting for application startup.
04-03 16:16:58 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:16:58 uvicorn.error INFO     Application startup complete.
04-03 16:16:58 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:17:10 uvicorn.access INFO     192.168.103.48:61826 - "GET /home/student-information/ HTTP/1.1" 200
04-03 16:17:17 uvicorn.access INFO     192.168.103.48:61827 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:17:21 uvicorn.access INFO     192.168.103.48:61827 - "GET /home/student-grades/ HTTP/1.1" 200
04-03 16:19:20 uvicorn.error INFO     Shutting down
04-03 16:19:20 uvicorn.error INFO     Finished server process [27156]
04-03 16:19:23 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:19:23 uvicorn.error INFO     Started server process [26812]
04-03 16:19:23 uvicorn.error INFO     Waiting for application startup.
04-03 16:19:23 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:19:23 uvicorn.error INFO     Application startup complete.
04-03 16:19:23 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:19:25 uvicorn.access INFO     192.168.103.48:61831 - "GET /home/student-grades/ HTTP/1.1" 200
04-03 16:19:35 uvicorn.access INFO     192.168.103.48:61832 - "GET /home/student-information/ HTTP/1.1" 200
04-03 16:20:28 uvicorn.error INFO     Shutting down
04-03 16:20:28 uvicorn.error INFO     Finished server process [26812]
04-03 16:20:35 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:20:36 uvicorn.error INFO     Started server process [14928]
04-03 16:20:36 uvicorn.error INFO     Waiting for application startup.
04-03 16:20:36 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:20:36 uvicorn.error INFO     Application startup complete.
04-03 16:20:36 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:20:39 uvicorn.access INFO     192.168.103.48:61836 - "GET /home/student-information/ HTTP/1.1" 200
04-03 16:21:45 uvicorn.error INFO     Shutting down
04-03 16:21:46 uvicorn.error INFO     Finished server process [14928]
04-03 16:21:48 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:21:48 uvicorn.error INFO     Started server process [25376]
04-03 16:21:48 uvicorn.error INFO     Waiting for application startup.
04-03 16:21:48 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:21:48 uvicorn.error INFO     Application startup complete.
04-03 16:21:48 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:21:50 uvicorn.access INFO     192.168.103.48:61841 - "GET /home/student-information/ HTTP/1.1" 200
04-03 16:22:20 uvicorn.error INFO     Shutting down
04-03 16:22:20 uvicorn.error INFO     Finished server process [25376]
04-03 16:22:29 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:22:30 uvicorn.error INFO     Started server process [25204]
04-03 16:22:30 uvicorn.error INFO     Waiting for application startup.
04-03 16:22:30 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:22:30 uvicorn.error INFO     Application startup complete.
04-03 16:22:30 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:22:32 uvicorn.access INFO     192.168.103.48:61845 - "GET /home/student-information/ HTTP/1.1" 200
04-03 16:23:34 uvicorn.error INFO     Shutting down
04-03 16:23:35 uvicorn.error INFO     Finished server process [25204]
04-03 16:23:37 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:23:38 uvicorn.error INFO     Started server process [2640]
04-03 16:23:38 uvicorn.error INFO     Waiting for application startup.
04-03 16:23:38 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:23:38 uvicorn.error INFO     Application startup complete.
04-03 16:23:38 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:23:44 uvicorn.access INFO     192.168.103.48:61862 - "GET /home/student-information/ HTTP/1.1" 200
04-03 16:25:19 uvicorn.error INFO     Shutting down
04-03 16:25:19 uvicorn.error INFO     Finished server process [2640]
04-03 16:25:26 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:25:26 uvicorn.error INFO     Started server process [23568]
04-03 16:25:26 uvicorn.error INFO     Waiting for application startup.
04-03 16:25:26 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:25:26 uvicorn.error INFO     Application startup complete.
04-03 16:25:26 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:25:28 uvicorn.access INFO     192.168.103.48:61870 - "GET /home/student-information/ HTTP/1.1" 200
04-03 16:29:17 uvicorn.access INFO     192.168.103.48:61878 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:32:59 uvicorn.error INFO     Shutting down
04-03 16:33:00 uvicorn.error INFO     Finished server process [23568]
04-03 16:33:03 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 16:33:03 uvicorn.error INFO     Started server process [1956]
04-03 16:33:03 uvicorn.error INFO     Waiting for application startup.
04-03 16:33:03 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 16:33:03 uvicorn.error INFO     Application startup complete.
04-03 16:33:03 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 16:33:06 uvicorn.access INFO     192.168.103.48:61887 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 16:33:11 uvicorn.access INFO     192.168.103.48:61887 - "GET /home/student-information/ HTTP/1.1" 200
04-03 16:33:12 uvicorn.access INFO     192.168.103.48:61887 - "GET /home/student-grades/ HTTP/1.1" 200
04-03 17:13:58 uvicorn.error INFO     Shutting down
04-03 17:13:58 uvicorn.error INFO     Finished server process [1956]
04-03 17:14:01 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 17:14:02 uvicorn.error INFO     Started server process [18516]
04-03 17:14:02 uvicorn.error INFO     Waiting for application startup.
04-03 17:14:02 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 17:14:02 uvicorn.error INFO     Application startup complete.
04-03 17:14:02 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 17:19:08 uvicorn.error INFO     Shutting down
04-03 17:19:08 uvicorn.error INFO     Finished server process [18516]
04-03 17:19:11 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 17:19:12 uvicorn.error INFO     Started server process [24504]
04-03 17:19:12 uvicorn.error INFO     Waiting for application startup.
04-03 17:19:12 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 17:19:12 uvicorn.error INFO     Application startup complete.
04-03 17:19:12 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 17:19:20 uvicorn.error ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 235, in _get_response_async
    callback, callback_args, callback_kwargs = self.resolve_request(request)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\asgi.py", line 170, in __call__
    await self.handle(scope, receive, send)
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\asgi.py", line 216, in handle
    task.result()
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\asgi.py", line 193, in process_request
    response = await self.run_get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\asgi.py", line 252, in run_get_response
    response = await self.get_response_async(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 162, in get_response_async
    response = await self._middleware_chain(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'
04-03 17:19:20 uvicorn.access INFO     192.168.103.48:62191 - "GET /home/student-grades/ HTTP/1.1" 500
04-03 17:19:28 uvicorn.error ERROR    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 235, in _get_response_async
    callback, callback_args, callback_kwargs = self.resolve_request(request)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\asgi.py", line 170, in __call__
    await self.handle(scope, receive, send)
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\asgi.py", line 216, in handle
    task.result()
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\asgi.py", line 193, in process_request
    response = await self.run_get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\asgi.py", line 252, in run_get_response
    response = await self.get_response_async(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 162, in get_response_async
    response = await self._middleware_chain(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 536, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 69, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 428, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 411, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\debug.py", line 102, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 686, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\TSMC\TSMC\TSMC\urls.py", line 27
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
                                                                                                                                     ^
SyntaxError: unmatched ')'
04-03 17:19:28 uvicorn.access INFO     192.168.103.48:62194 - "GET /home/index2/ HTTP/1.1" 500
04-03 17:32:46 uvicorn.error INFO     Shutting down
04-03 17:32:46 uvicorn.error INFO     Finished server process [24504]
04-03 17:32:52 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 17:32:53 uvicorn.error INFO     Started server process [25248]
04-03 17:32:53 uvicorn.error INFO     Waiting for application startup.
04-03 17:32:53 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 17:32:53 uvicorn.error INFO     Application startup complete.
04-03 17:32:53 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 17:32:59 uvicorn.access INFO     192.168.103.48:62342 - "GET /home/ HTTP/1.1" 200
04-03 17:33:02 uvicorn.access INFO     192.168.103.48:62343 - "GET /home/ HTTP/1.1" 200
04-03 17:33:11 django.request ERROR    Internal Server Error: /scores/detail/
Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: scores_course

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\TSMC\TSMC\scores\views.py", line 30, in detail
    return render(request, 'scores/detail.html', locals())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 198, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lu\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: scores_course
04-03 17:33:11 uvicorn.access INFO     192.168.103.48:62344 - "GET /scores/detail/ HTTP/1.1" 500
04-03 17:33:25 uvicorn.access INFO     192.168.103.48:62349 - "GET /welcome/logout/ HTTP/1.1" 302
04-03 17:33:26 uvicorn.access INFO     192.168.103.48:62349 - "GET /home/ HTTP/1.1" 200
04-03 17:33:31 uvicorn.access INFO     192.168.103.48:62349 - "GET /welcome/login/ HTTP/1.1" 200
04-03 17:33:33 uvicorn.access INFO     192.168.103.48:62353 - "GET /welcome/register/ HTTP/1.1" 200
04-03 17:34:20 uvicorn.access INFO     192.168.103.48:62360 - "POST /welcome/register/ HTTP/1.1" 302
04-03 17:34:20 uvicorn.access INFO     192.168.103.48:62360 - "GET /home/ HTTP/1.1" 200
04-03 17:34:25 django.request WARNING  Not Found: /score/student-grades/
04-03 17:34:25 uvicorn.access INFO     192.168.103.48:62362 - "GET /score/student-grades/ HTTP/1.1" 404
04-03 17:35:35 uvicorn.access INFO     192.168.103.48:62378 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 17:35:52 uvicorn.access INFO     192.168.103.48:62382 - "GET /home/student-information/ HTTP/1.1" 200
04-03 17:35:56 django.request WARNING  Not Found: /home/student-grades/
04-03 17:35:56 uvicorn.access INFO     192.168.103.48:62385 - "GET /home/student-grades/ HTTP/1.1" 404
04-03 17:38:43 uvicorn.error INFO     Shutting down
04-03 17:38:43 uvicorn.error INFO     Finished server process [25248]
04-03 17:40:37 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 17:40:37 uvicorn.error INFO     Started server process [9816]
04-03 17:40:37 uvicorn.error INFO     Waiting for application startup.
04-03 17:40:37 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 17:40:37 uvicorn.error INFO     Application startup complete.
04-03 17:40:37 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 17:40:43 uvicorn.access INFO     192.168.103.48:62420 - "GET /home/student-information/ HTTP/1.1" 200
04-03 17:40:44 django.request WARNING  Not Found: /home/student-grades/
04-03 17:40:44 uvicorn.access INFO     192.168.103.48:62420 - "GET /home/student-grades/ HTTP/1.1" 404
04-03 17:44:45 uvicorn.error INFO     Shutting down
04-03 17:44:45 uvicorn.error INFO     Finished server process [9816]
04-03 17:44:49 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 17:44:50 uvicorn.error INFO     Started server process [6616]
04-03 17:44:50 uvicorn.error INFO     Waiting for application startup.
04-03 17:44:50 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 17:44:50 uvicorn.error INFO     Application startup complete.
04-03 17:44:50 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 17:44:51 uvicorn.access INFO     192.168.103.48:62435 - "GET /home/student-information/ HTTP/1.1" 200
04-03 17:44:54 uvicorn.access INFO     192.168.103.48:62435 - "GET /scores/student-grades/ HTTP/1.1" 200
04-03 17:47:05 uvicorn.error INFO     Shutting down
04-03 17:47:05 uvicorn.error INFO     Finished server process [6616]
04-03 17:47:08 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 17:47:08 uvicorn.error INFO     Started server process [20512]
04-03 17:47:08 uvicorn.error INFO     Waiting for application startup.
04-03 17:47:08 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 17:47:08 uvicorn.error INFO     Application startup complete.
04-03 17:47:08 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 17:47:11 uvicorn.access INFO     192.168.103.48:62440 - "GET /scores/student-grades/ HTTP/1.1" 200
04-03 17:47:58 uvicorn.error INFO     Shutting down
04-03 17:47:58 uvicorn.error INFO     Finished server process [20512]
04-03 17:48:02 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 17:48:03 uvicorn.error INFO     Started server process [16536]
04-03 17:48:03 uvicorn.error INFO     Waiting for application startup.
04-03 17:48:03 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 17:48:03 uvicorn.error INFO     Application startup complete.
04-03 17:48:03 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 17:48:04 uvicorn.access INFO     192.168.103.48:62445 - "GET /scores/student-grades/ HTTP/1.1" 200
04-03 17:48:37 uvicorn.error INFO     Shutting down
04-03 17:48:37 uvicorn.error INFO     Finished server process [16536]
04-03 17:48:40 uvicorn.error INFO     Will watch for changes in these directories: ['D:\\TSMC\\TSMC']
04-03 17:48:41 uvicorn.error INFO     Started server process [23260]
04-03 17:48:41 uvicorn.error INFO     Waiting for application startup.
04-03 17:48:41 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
04-03 17:48:41 uvicorn.error INFO     Application startup complete.
04-03 17:48:41 uvicorn.error INFO     Uvicorn running on http://192.168.103.48:8701 (Press CTRL+C to quit)
04-03 17:48:42 uvicorn.access INFO     192.168.103.48:62450 - "GET /scores/student-grades/ HTTP/1.1" 200
04-03 17:49:03 uvicorn.access INFO     192.168.103.48:62451 - "GET /home/questionnaire/ HTTP/1.1" 200
04-03 17:49:20 uvicorn.access INFO     192.168.103.48:62452 - "GET /home/student-information/ HTTP/1.1" 200
04-03 17:50:22 uvicorn.access INFO     192.168.103.48:62454 - "GET /scores/student-grades/ HTTP/1.1" 200
