08-13 15:41:27 uvicorn.error INFO     Will watch for changes in these directories: ['C:\\django_test\\Duckbubi']
08-13 15:41:28 uvicorn.error INFO     Started server process [18832]
08-13 15:41:28 uvicorn.error INFO     Waiting for application startup.
08-13 15:41:28 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
08-13 15:41:28 uvicorn.error INFO     Application startup complete.
08-13 15:41:28 uvicorn.error INFO     Uvicorn running on http://26.37.7.101:80 (Press CTRL+C to quit)
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61276 - "GET / HTTP/1.1" 302
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61276 - "GET /home/ HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61276 - "GET /static/assets/vendor/aos/aos.css HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61282 - "GET /static/assets/vendor/glightbox/css/glightbox.min.css HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61280 - "GET /static/assets/vendor/bootstrap-icons/bootstrap-icons.css HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61279 - "GET /static/assets/vendor/bootstrap/css/bootstrap.min.css HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61281 - "GET /static/assets/vendor/boxicons/css/boxicons.min.css HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61278 - "GET /static/assets/vendor/fontawesome-free/css/all.min.css HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61276 - "GET /static/assets/vendor/swiper/swiper-bundle.min.css HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61282 - "GET /static/assets/css/style.css HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61280 - "GET /static/assets/vendor/aos/aos.js HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61281 - "GET /static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61282 - "GET /static/assets/vendor/php-email-form/validate.js HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61279 - "GET /static/assets/vendor/glightbox/js/glightbox.min.js HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61278 - "GET /static/assets/vendor/isotope-layout/isotope.pkgd.min.js HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61276 - "GET /static/assets/vendor/swiper/swiper-bundle.min.js HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61282 - "GET /static/assets/vendor/bootstrap-icons/fonts/bootstrap-icons.woff2?24e3eb84d0bcaf83d77f904c78ac1f47 HTTP/1.1" 200
08-13 15:41:34 uvicorn.access INFO     26.37.7.101:61280 - "GET /static/assets/js/main.js HTTP/1.1" 200
08-13 15:41:35 django.request WARNING  Not Found: /favicon.ico
08-13 15:41:35 uvicorn.access INFO     26.37.7.101:61280 - "GET /favicon.ico HTTP/1.1" 404
08-13 15:41:50 uvicorn.access INFO     26.37.7.101:61344 - "GET /home/ HTTP/1.1" 200
08-13 15:41:51 django.request WARNING  Not Found: /favicon.ico
08-13 15:41:51 uvicorn.access INFO     26.37.7.101:61344 - "GET /favicon.ico HTTP/1.1" 404
08-13 15:41:53 uvicorn.access INFO     26.37.7.101:61359 - "GET /welcome/login/ HTTP/1.1" 200
08-13 15:41:56 uvicorn.access INFO     26.37.7.101:61359 - "POST /welcome/login/ HTTP/1.1" 302
08-13 15:41:56 uvicorn.access INFO     26.37.7.101:61359 - "GET /home/ HTTP/1.1" 200
08-13 16:17:12 uvicorn.error INFO     Shutting down
08-13 16:17:12 uvicorn.error INFO     Finished server process [18832]
08-13 16:17:13 uvicorn.error INFO     Will watch for changes in these directories: ['C:\\django_test\\Duckbubi']
08-13 16:17:14 uvicorn.error INFO     Started server process [6360]
08-13 16:17:14 uvicorn.error INFO     Waiting for application startup.
08-13 16:17:14 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
08-13 16:17:14 uvicorn.error INFO     Application startup complete.
08-13 16:17:14 uvicorn.error INFO     Uvicorn running on http://26.37.7.101:80 (Press CTRL+C to quit)
08-13 16:17:16 uvicorn.access INFO     26.37.7.101:61743 - "GET /home/ HTTP/1.1" 200
08-13 16:17:17 django.request WARNING  Not Found: /home/chatroom/
08-13 16:17:17 uvicorn.access INFO     26.37.7.101:61743 - "GET /home/chatroom/ HTTP/1.1" 404
08-13 16:17:23 django.request WARNING  Not Found: /home/chatroom/
08-13 16:17:23 uvicorn.access INFO     26.37.7.101:61744 - "GET /home/chatroom/ HTTP/1.1" 404
08-13 16:19:26 uvicorn.error INFO     Shutting down
08-13 16:19:26 uvicorn.error INFO     Finished server process [6360]
08-13 16:19:27 uvicorn.error INFO     Will watch for changes in these directories: ['C:\\django_test\\Duckbubi']
08-13 16:19:28 uvicorn.error INFO     Started server process [20912]
08-13 16:19:28 uvicorn.error INFO     Waiting for application startup.
08-13 16:19:28 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
08-13 16:19:28 uvicorn.error INFO     Application startup complete.
08-13 16:19:28 uvicorn.error INFO     Uvicorn running on http://26.37.7.101:80 (Press CTRL+C to quit)
08-13 16:19:30 uvicorn.access INFO     26.37.7.101:61797 - "GET /home/ HTTP/1.1" 200
08-13 16:19:30 django.request ERROR    Internal Server Error: /home/chatroom/
Traceback (most recent call last):
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\user\Envs\django\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\user\Envs\django\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\django_test\Duckbubi\home\views.py", line 48, in chatroom
    api_url = reverse('get_user_profile')
  File "C:\Users\user\Envs\django\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\user\Envs\django\lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'get_user_profile' not found. 'get_user_profile' is not a valid view function or pattern name.
08-13 16:19:30 uvicorn.access INFO     26.37.7.101:61797 - "GET /home/chatroom/ HTTP/1.1" 500
08-13 16:19:59 uvicorn.error INFO     Shutting down
08-13 16:19:59 uvicorn.error INFO     Finished server process [20912]
08-13 16:20:01 uvicorn.error INFO     Will watch for changes in these directories: ['C:\\django_test\\Duckbubi']
08-13 16:20:01 uvicorn.error INFO     Started server process [1816]
08-13 16:20:01 uvicorn.error INFO     Waiting for application startup.
08-13 16:20:01 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
08-13 16:20:01 uvicorn.error INFO     Application startup complete.
08-13 16:20:01 uvicorn.error INFO     Uvicorn running on http://26.37.7.101:80 (Press CTRL+C to quit)
08-13 16:20:04 django.request ERROR    Internal Server Error: /home/chatroom/
Traceback (most recent call last):
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\user\Envs\django\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\user\Envs\django\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\django_test\Duckbubi\home\views.py", line 48, in chatroom
    api_url = reverse('get_user_profile')
  File "C:\Users\user\Envs\django\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\user\Envs\django\lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'get_user_profile' not found. 'get_user_profile' is not a valid view function or pattern name.
08-13 16:20:04 uvicorn.access INFO     26.37.7.101:61808 - "GET /home/chatroom/ HTTP/1.1" 500
08-13 16:20:46 uvicorn.error INFO     Shutting down
08-13 16:20:46 uvicorn.error INFO     Finished server process [1816]
08-13 16:20:47 uvicorn.error INFO     Will watch for changes in these directories: ['C:\\django_test\\Duckbubi']
08-13 16:20:47 uvicorn.error INFO     Started server process [7424]
08-13 16:20:48 uvicorn.error INFO     Waiting for application startup.
08-13 16:20:48 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
08-13 16:20:48 uvicorn.error INFO     Application startup complete.
08-13 16:20:48 uvicorn.error INFO     Uvicorn running on http://26.37.7.101:80 (Press CTRL+C to quit)
08-13 16:20:49 django.request ERROR    Internal Server Error: /home/chatroom/
Traceback (most recent call last):
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\user\Envs\django\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\user\Envs\django\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\django_test\Duckbubi\home\views.py", line 48, in chatroom
    api_url = reverse('get_user_profile')
  File "C:\Users\user\Envs\django\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\user\Envs\django\lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'get_user_profile' not found. 'get_user_profile' is not a valid view function or pattern name.
08-13 16:20:49 uvicorn.access INFO     26.37.7.101:61821 - "GET /home/chatroom/ HTTP/1.1" 500
08-13 16:20:52 django.request ERROR    Internal Server Error: /home/chatroom/
Traceback (most recent call last):
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\user\Envs\django\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\user\Envs\django\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\django_test\Duckbubi\home\views.py", line 48, in chatroom
    api_url = reverse('get_user_profile')
  File "C:\Users\user\Envs\django\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\user\Envs\django\lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'get_user_profile' not found. 'get_user_profile' is not a valid view function or pattern name.
08-13 16:20:52 uvicorn.access INFO     26.37.7.101:61821 - "GET /home/chatroom/ HTTP/1.1" 500
08-13 16:22:05 uvicorn.error INFO     Shutting down
08-13 16:22:05 uvicorn.error INFO     Finished server process [7424]
08-13 16:22:07 uvicorn.error INFO     Will watch for changes in these directories: ['C:\\django_test\\Duckbubi']
08-13 16:22:08 uvicorn.error INFO     Started server process [12836]
08-13 16:22:08 uvicorn.error INFO     Waiting for application startup.
08-13 16:22:08 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
08-13 16:22:08 uvicorn.error INFO     Application startup complete.
08-13 16:22:08 uvicorn.error INFO     Uvicorn running on http://26.37.7.101:80 (Press CTRL+C to quit)
08-13 16:22:09 uvicorn.access INFO     26.37.7.101:61845 - "GET /welcome/logout/ HTTP/1.1" 302
08-13 16:22:09 uvicorn.access INFO     26.37.7.101:61845 - "GET /home/ HTTP/1.1" 200
08-13 16:22:12 uvicorn.access INFO     26.37.7.101:61845 - "GET /welcome/login/ HTTP/1.1" 200
08-13 16:22:14 uvicorn.access INFO     26.37.7.101:61845 - "POST /welcome/login/ HTTP/1.1" 302
08-13 16:22:14 uvicorn.access INFO     26.37.7.101:61845 - "GET /home/ HTTP/1.1" 200
08-13 16:22:16 django.request ERROR    Internal Server Error: /home/chatroom/
Traceback (most recent call last):
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "C:\Users\user\Envs\django\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\user\Envs\django\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\Envs\django\lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "C:\django_test\Duckbubi\home\views.py", line 48, in chatroom
    api_url = reverse('get_user_profile')
  File "C:\Users\user\Envs\django\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\user\Envs\django\lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'get_user_profile' not found. 'get_user_profile' is not a valid view function or pattern name.
08-13 16:22:16 uvicorn.access INFO     26.37.7.101:61845 - "GET /home/chatroom/ HTTP/1.1" 500
08-13 16:25:35 uvicorn.error INFO     Shutting down
08-13 16:25:36 uvicorn.error INFO     Finished server process [12836]
08-13 16:25:37 uvicorn.error INFO     Will watch for changes in these directories: ['C:\\django_test\\Duckbubi']
08-13 16:25:44 uvicorn.error INFO     Started server process [21484]
08-13 16:25:44 uvicorn.error INFO     Waiting for application startup.
08-13 16:25:44 uvicorn.error INFO     ASGI 'lifespan' protocol appears unsupported.
08-13 16:25:44 uvicorn.error INFO     Application startup complete.
08-13 16:25:44 uvicorn.error INFO     Uvicorn running on http://26.37.7.101:80 (Press CTRL+C to quit)
08-13 16:25:45 uvicorn.access INFO     26.37.7.101:61909 - "GET /home/chatroom/ HTTP/1.1" 200
08-13 16:25:45 uvicorn.access INFO     26.37.7.101:61909 - "GET /home/chatroom/ HTTP/1.1" 200
08-13 16:26:05 uvicorn.access INFO     26.37.7.101:61910 - "GET /home/ HTTP/1.1" 200
08-13 16:26:12 uvicorn.access INFO     26.37.7.101:61911 - "GET /home/chatroom/ HTTP/1.1" 200
08-13 16:26:12 uvicorn.access INFO     26.37.7.101:61911 - "GET /home/chatroom/ HTTP/1.1" 200
08-13 16:26:25 uvicorn.error INFO     Shutting down
08-13 16:26:25 uvicorn.error INFO     Finished server process [21484]
